Play upgrade (#20)
* Play upgrade
- Update sbt configuration
- Fix simple deprecations
- JsonValidations and Joda reads/writes
- fix controllers
- use library auditconnector
- fix controller tests
- Fix WSClient usage

* - fix more deprecations

* - fix auth and tag/attr deprecations

* - fix content-type warning
- remove excessive mongo info logs

* - fix sbt config so that func tests run

* - fix coverage plugin version (NoClassDefFoundError)